import '../models/puzzle.dart';

final List<Puzzle> seedPuzzles = [
  //ZOMBIE THEME
  Puzzle(
    theme: 'Zombie',
    levelNumber: 1,
    storyText: 'You enter a contaminated lab. To create the antidote, you must collect all 10 ingredients before the infection spreads.',
    question: 'What has to be broken before you can use it?',
    acceptedAnswers: 'egg',
    rewardText: 'You obtained: protein sample',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 2,
    storyText: 'You locate a storage freezer labeled Stage 2 Compounds. A lock blocks your access. A sticky note reads: Only those who understand basics may proceed.',
    question: 'What gets wetter the more it dries?',
    acceptedAnswers: 'towel',
    rewardText: 'You obtained: solvent',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 3,
    storyText: 'You move deeper into the lab. A terminal flickers with a security question tied to chemical stability. You must answer correctly to continue synthesizing the cure.',
    question: 'What is always in front of you but cannot be seen?',
    acceptedAnswers: 'future',
    rewardText: 'You obtained: enzyme',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 4,
    storyText: 'The next chamber contains broken equipment and chemical spills. A console asks for a response before allowing you to proceed. Time is running out as the infection spreads.',
    question: 'I am tall when I am young and short when I am old. What am I?',
    acceptedAnswers: 'candle',
    rewardText: 'You obtained: catalyst',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 5,
    storyText: 'You find a sealed container labeled Core Compound. The lock requires logic, not science. The answer will grant access to a key part of the cure.',
    question: 'What month has 28 days?',
    acceptedAnswers: 'all|all of them|every month',
    rewardText: 'You obtained: compound base',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 6,
    storyText: 'The system begins combining your collected materials. A final check appears to confirm your understanding of basic lab tools. One wrong answer could delay everything.',
    question: 'Rearrange "CIDA" to form something used in science.',
    acceptedAnswers: 'acid',
    rewardText: 'You obtained: acid',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 7,
    storyText: 'You hear infected pounding on the lab doors. The cure must be completed quickly. The system asks one more question before unlocking advanced materials.',
    question: 'I have no life, but I can die. What am I?',
    acceptedAnswers: 'battery',
    rewardText: 'You obtained: energy source',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 8,
    storyText: 'The final formula begins to take shape. A numeric pattern appears on the screen, testing your ability to think under pressure. Solve it to stabilize the mixture.',
    question: '2, 6, 7, 21, 22, ?',
    acceptedAnswers: '66',
    rewardText: 'You obtained: stabilizer',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 9,
    storyText: 'The cure is almost ready. A simulation shows how the infection spreads rapidly. You must answer correctly to finalize the dosage.',
    question: 'A virus doubles every hour and fills a room in 24 hours. When was it half full?',
    acceptedAnswers: '23',
    rewardText: 'You obtained: dosage formula',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Zombie',
    levelNumber: 10,
    storyText: 'All ingredients are ready. The system requires one final confirmation before releasing the cure. This determines whether humanity survives.',
    question: 'Decode: 3-1-20',
    acceptedAnswers: 'cat',
    rewardText: 'Cure completed',
    isFinalLevel: 0,
  ),

  //TIME TRAVEL THEME
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 1,
    storyText: 'The time machine is broken and you are in the wrong time period. You must collect all 10 parts to restore it and return home.',
    question: 'What goes up but never comes down?',
    acceptedAnswers: 'age',
    rewardText: 'You obtained: power core',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 2,
    storyText: 'You inspect the machine. The interface requires simple logic to unlock components. You must restore basic functions first.',
    question: 'What has hands but cannot clap?',
    acceptedAnswers: 'clock',
    rewardText: 'You obtained: time dial',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 3,
    storyText: 'The system boots partially. A water-based cooling system needs activation. Solve the prompt to continue.',
    question: 'What runs but never walks?',
    acceptedAnswers: 'water',
    rewardText: 'You obtained: coolant',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 4,
    storyText: 'You notice a navigation module flickering. It requires pattern recognition to function again. Without it, you cannot return home.',
    question: '1, 4, 9, 16, 25, ?',
    acceptedAnswers: '36',
    rewardText: 'You obtained: navigation chip',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 5,
    storyText: 'The machine hums faintly. A message appears testing your understanding of physical objects. This part stabilizes the structure.',
    question: 'What can travel around the world while staying in one spot?',
    acceptedAnswers: 'stamp',
    rewardText: 'You obtained: signal transmitter',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 6,
    storyText: 'A security lock activates. It requires abstract thinking to proceed. Only correct reasoning will unlock the next part.',
    question: 'If you have me, you want to share me. If you share me, you do not have me. What am I?',
    acceptedAnswers: 'secret',
    rewardText: 'You obtained: encryption key',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 7,
    storyText: 'The system begins recalibrating. One last logic test appears before advanced systems unlock. Focus carefully.',
    question: 'What begins with T, ends with T, and has T in it?',
    acceptedAnswers: 'teapot',
    rewardText: 'You obtained: containment unit',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 8,
    storyText: 'Energy surges through the machine. A mathematical sequence appears. Solving it will stabilize power flow.',
    question: '2, 6, 7, 21, 22, ?',
    acceptedAnswers: '66',
    rewardText: 'You obtained: energy regulator',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 9,
    storyText: 'The machine prepares for activation. One final trick question appears. Answer correctly to avoid system failure.',
    question: 'Where do you bury survivors of a plane crash?',
    acceptedAnswers: 'nowhere',
    rewardText: 'You obtained: safety override',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Time Travel',
    levelNumber: 10,
    storyText: 'Everything is ready. The machine powers up, but requires one final confirmation. This determines whether you make it home.',
    question: 'I speak without a mouth and hear without ears. What am I?',
    acceptedAnswers: 'echo',
    rewardText: 'Time machine restored',
    isFinalLevel: 0,
  ),

  //MURDER MYSTERY THEME
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 1,
    storyText: 'The dinner party ended in chaos when the host suddenly collapsed at the table. The doctor later confirmed it was poison. Four people were present: Chef Marco, Butler James, Lila the victim\'s best friend, and Mr. Grant, a business partner. Each claims innocence, but the truth is hidden somewhere in their stories.',
    question: 'I enter quietly, hidden from sight.\nNo blade, no force, yet I still take life.\nWhat am I?',
    acceptedAnswers: 'poison',
    rewardText: 'Clue 1: The cause of death was not obvious to anyone at the table',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 2,
    storyText: 'No one recalls seeing anything unusual happen. There was no struggle, no sudden movement, and nothing that drew attention. Whatever happened, it happened without anyone noticing.',
    question: 'I act without being seen,\nand leave no mark behind.\nWhat am I?',
    acceptedAnswers: 'silent|hidden|unseen',
    rewardText: 'Clue 2: The act happened without drawing attention',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 3,
    storyText: 'You begin to think about timing. Everyone remembers the dinner, but not every second of it. The moment that mattered may have passed unnoticed.',
    question: 'I come and go, yet leave no trace.\nMiss me once, I am gone without a face.\nWhat am I?',
    acceptedAnswers: 'moment|time',
    rewardText: 'Clue 3: The act happened in a brief, unnoticed moment',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 4,
    storyText: 'You reconsider where everyone was during the dinner. Some stayed in one place, while others moved around. If the act required the right moment, then movement becomes important.',
    question: 'The more you take, the more you leave behind.\nWhat am I?',
    acceptedAnswers: 'footsteps|steps',
    rewardText: 'Clue 4: Not everyone stayed where they were',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 5,
    storyText: 'You review the suspects\' reasons for being there. Some had strong emotional ties, while others had financial interests. But having a reason does not mean having the ability.',
    question: 'I explain why, but not how.\nI give a reason, but not the act.\nWhat am I?',
    acceptedAnswers: 'motive|reason',
    rewardText: 'Clue 5: Having a reason does not mean someone committed the crime',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 6,
    storyText: 'You compare each person\'s story with what others remember. Some accounts match perfectly, while others leave small gaps. Those gaps may matter more than they seem.',
    question: 'I tell where you were,\nso you cannot be elsewhere.\nWhat am I?',
    acceptedAnswers: 'alibi',
    rewardText: 'Clue 6: Some stories confirm where people were the entire time',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 7,
    storyText: 'One detail stands out from a witness account. Someone was seen somewhere they did not mention. That inconsistency may be the key.',
    question: 'I show the truth, even when denied.\nI place you somewhere you tried to hide.\nWhat am I?',
    acceptedAnswers: 'evidence|proof',
    rewardText: 'Clue 7: Someone was seen away from where they claimed to be',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 8,
    storyText: 'You now focus on how the poison could have been delivered. It had to reach the victim without suspicion, hidden in something trusted.',
    question: 'I travel inside what you consume,\nhidden where trust is assumed.\nWhat am I?',
    acceptedAnswers: 'food|meal|dish',
    rewardText: 'Clue 8: The poison was delivered through something consumed',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 9,
    storyText: 'Everything begins to connect. The method, the timing, the movement, and the access all point in one direction. Only one person had complete control over what was prepared and served.',
    question: 'I decide what is made and what is served,\ntrusted by all, yet rarely observed.\nWho am I?',
    acceptedAnswers: 'chef|cook',
    rewardText: 'Clue 9: The person who controlled the meal had the opportunity',
    isFinalLevel: 0,
  ),
  Puzzle(
    theme: 'Murder Mystery',
    levelNumber: 10,
    storyText: 'You review everything you discovered throughout the investigation. Each clue reveals a piece of the truth. When placed together, they point clearly to one person.',
    question: 'Who is the killer?',
    acceptedAnswers: 'chef marco|marco|chef',
    rewardText: 'Case closed',
    isFinalLevel: 1,
  ),
];